export const implementations = [
  { id: "python-jsonschema", name: "jsonschema (Python)", owner: "python-jsonschema", repo: "jsonschema" },
  { id: "php-opis-json-schema", name: "opis/json-schema", owner: "opis", repo: "json-schema" },
  { id: "rust-boon", name: "boon", owner: "santhosh-tekuri", repo: "boon" },
  { id: "cpp-jsoncons", name: "jsoncons", owner: "danielaparker", repo: "jsoncons" },
  { id: "java-networknt-json-schema-validator", name: "networknt", owner: "networknt", repo: "json-schema-validator" },
  { id: "scala-rc-circe-json-validator", name: "rc-circe", owner: "reactivecore", repo: "rc-circe-json-schema" },
  { id: "java-openapiprocessor", name: "openapi-processor", owner: "openapi-processor", repo: "openapi-parser" },
  { id: "java-jsonschemafriend", name: "jsonschemafriend", owner: "jimblackler", repo: "jsonschemafriend" },
  { id: "java-sjf4j", name: "sjf4j", owner: "sjf4j-projects", repo: "sjf4j" },
  { id: "rust-jsonschema", name: "jsonschema-rs", owner: "Stranger6667", repo: "jsonschema-rs" },
  { id: "kotlin-kmp-json-schema-validator", name: "kmp-validator", owner: "OptimumCode", repo: "json-schema-validator" },
  { id: "cpp-blaze", name: "blaze", owner: "sourcemeta", repo: "blaze" },
  { id: "go-jsonschema", name: "jsonschema (Go)", owner: "santhosh-tekuri", repo: "jsonschema" },
  { id: "java-json-schema", name: "dev.harrel.json-schema", owner: "harrel56", repo: "json-schema" },
  { id: "python-jschon", name: "jschon", owner: "marksparkza", repo: "jschon" },
  { id: "dotnet-newtonsoft-json-schema", name: "Newtonsoft.Json.Schema", owner: "JamesNK", repo: "Newtonsoft.Json.Schema" },
  { id: "dotnet-jsonschema-net", name: "JsonSchema.Net", owner: "gregsdennis", repo: "json-everything" },
  { id: "java-json-schema-react", name: "georgeakulov/json-schema", owner: "georgeakulov", repo: "json-schema" },
  { id: "js-schemasafe", name: "schemasafe", owner: "ExodusMovement", repo: "schemasafe" },
  { id: "dotnet-corvus-jsonschema", name: "Corvus.JsonSchema", owner: "corvus-dotnet", repo: "corvus.jsonschema" },
  { id: "js-json-schema", name: "cfworker", owner: "cfworker", repo: "cfworker" },
  { id: "js-ajv", name: "ajv", owner: "ajv-validator", repo: "ajv" },
  { id: "js-ajv-plus", name: "ajv-plus", owner: "theflashlabs", repo: "ajv-plus" },
  { id: "ts-vscode-json-languageservice", name: "vscode-json-languageservice", owner: "microsoft", repo: "vscode-json-languageservice" },
  { id: "js-hyperjump", name: "hyperjump", owner: "hyperjump-io", repo: "json-schema" },
  { id: "ruby-json_schemer", name: "json_schemer", owner: "davishmcclurg", repo: "json_schemer" },
  { id: "python-jsu", name: "jsu", owner: "zx80", repo: "json-schema-utils" },
  { id: "perl-json-schema-modern", name: "JSON-Schema-Modern", owner: "karenetheridge", repo: "JSON-Schema-Modern" },
  { id: "swift-swift-json-schema", name: "swift-json-schema", owner: "ajevans99", repo: "swift-json-schema" },
  { id: "elixir-jsv", name: "jsv", owner: "lud", repo: "jsv" },
];
